### ISSUE TITLE
New Vobject::Property and Vobject::Component classes to be defined

### ISSUE THREAD

**Issue by PeterTKY** [riboseinc/ruby-vobject#3]
class Vobject::Property
- will be the base class of the future property classes of iCalendar and vCard
- Example:
```ruby
uid = Vobject::Property::UID.new({:value=>"uid4@example.com"})
uid.to_s
=> "UID:uid4@example.com"
```
- should handle folding/unfolding as stated in RFC 5545 and 6350

Vobject::Component
- will be the base class of the future component classes of iCalendar and vCard
- Example:
```ruby
valarm = Vobject::Component::Valarm.new([{:ACTION=>{:value=>"AUDIO"}}, {:TRIGGER=>{:value=>"19980403T120000Z"}}, {:ATTACH=>{:params=>{:FMTTYPE=>"audio/basic"}, :value=>"http://example.com/pub/audio-files/ssbanner.aud"}}, {:REPEAT=>{:value=>"4"}}, {:DURATION=>{:value=>"PT1H"}}])
valarm.to_s
=> "BEGIN:VALARM\nACTION:AUDIO\nTRIGGER:19980403T120000Z\nATTACH;FMTTYPE=audio/basic:http://example.com/pub/audio-\n\tfiles/ssbanner.aud\nREPEAT:4\nDURATION:PT1H\nEND:VALARM"
```

**Comment by PeterTKY** [comment]
Have defined the two new classes. Some new specs required...

**Comment by ronaldtse** [comment]
Parsing should output an object hierarchy instead of a hash:

Now:
```ruby
{:VCALENDAR=>{:VERSION=>{:value=>"2.0"},...}
```

Should be:
```ruby
Vobject::Component::Vcalendar(:properties => Vobject::Property::Version ...)
```

**Comment by opoudjis** [comment]
For my sanity, I think I'm going to keep the parse generating a hash, and convert that hash into an object in postprocessing.

**Comment by opoudjis** [comment]
I've addressed this, but let me confirm that you like the solution.

Some properties have multiple values, and each value can have its own set of parameters.

For that reason, the Vobject:Property value can be either, for a single value:

- key
- linegroup
- value
- params

or, for multiple values:

- key
- multiple: Array of Vobject:Property

Example instance of a parsed object:

#<Vobject::Component:0x007fc0921cfe08
 @children=
  [#<Vobject::Property:0x007fc0921cf908
    @group=nil,
    @params=nil,
    @prop_name=:VERSION,
    @value="2.0">,
   #<Vobject::Property:0x007fc0921cf4a8
    @group=nil,
    @params=nil,
    @prop_name=:PRODID,
    @value="a">,
   #<Vobject::Property:0x007fc0921cf020
    @multiple=
     [#<Vobject::Property:0x007fc0921cef58
       @group=nil,
       @params={:ALTID=>"3"},
       @prop_name=:KIND,
       @value="individual">,
      #<Vobject::Property:0x007fc0921cee90
       @group=nil,
       @params={:ALTID=>"3"},
       @prop_name=:KIND,
       @value="group">,
      #<Vobject::Property:0x007fc0921cee18
       @group=nil,
       @params={:ALTID=>"3"},
       @prop_name=:KIND,
       @value="nec">],
    @prop_name=:KIND>,
   #<Vobject::Component:0x007fc0921cea58
    @children=
     [#<Vobject::Property:0x007fc0921ce7b0
       @group=nil,
       @params=nil,
       @prop_name=:DTSTAMP,
       @value=1998-01-30 13:45:00 UTC>,
      #<Vobject::Property:0x007fc0921ce4b8
       @group=nil,
       @params=nil,
       @prop_name=:UID,
       @value="uid4@example.com">,
      #<Vobject::Property:0x007fc0921ce1c0
       @group=nil,
       @params=nil,
       @prop_name=:GEO,
       @value={:lat=>1.0, :long=>2.0}>,
      #<Vobject::Property:0x007fc0921cdea0
       @group=nil,
       @params=nil,
       @prop_name=:PERCENT_COMPLETE,
       @value=1>,
      #<Vobject::Property:0x007fc0921cdbd0
       @group=nil,
       @params=nil,
       @prop_name=:ORGANIZER,
       @value="mailto:unclesam@example.com">,
      #<Vobject::Property:0x007fc0921cd838
       @multiple=
        [#<Vobject::Property:0x007fc0921cd7e8
          @group=nil,
          @params={:ALTREP=>"ACCEPTED"},
          @prop_name=:ATTENDEE,
          @value="mailto:jqpublic@example.com">,
         #<Vobject::Property:0x007fc0921cd770
          @group=nil,
          @params=
           {:DELEGATED_TO=>
             ["mailto:jqpublic@example.com", "mailto:jdoe@example.com"]},
          @prop_name=:ATTENDEE,
          @value="mailto:jsmith@example.com">],
       @prop_name=:ATTENDEE>,
      #<Vobject::Property:0x007fc0921cd478
       @group=nil,
       @params=nil,
       @prop_name=:DUE,
       @value=1998-04-15 00:00:00 +1000>,
      #<Vobject::Property:0x007fc0921cd1a8
       @group=nil,
       @params=nil,
       @prop_name=:STATUS,
       @value="NEEDS-ACTION">,
      #<Vobject::Property:0x007fc0921cced8
       @group=nil,
       @params=nil,
       @prop_name=:SUMMARY,
       @value="Submit Income Taxes">],
    @comp_name=:VTODO>,
   #<Vobject::Component:0x007fc0921ccbe0
    @children=
     [#<Vobject::Property:0x007fc0921cc960
       @group=nil,
       @params=nil,
       @prop_name=:ACTION,
       @value="AUDIO">,
      #<Vobject::Property:0x007fc0921cc668
       @group=nil,
       @params=nil,
       @prop_name=:TRIGGER,
       @value=1998-04-03 12:00:00 UTC>,
      #<Vobject::Property:0x007fc0921cc370
       @group=nil,
       @params={:FMTTYPE=>"audio/basic"},
       @prop_name=:ATTACH,
       @value="http://example.com/pub/audio-files/ssbanner.aud">,
      #<Vobject::Property:0x007fc0921cc0a0
       @group=nil,
       @params=nil,
       @prop_name=:REPEAT,
       @value=4>,
      #<Vobject::Property:0x007fc0921c7e60
       @group=nil,
       @params=nil,
       @prop_name=:DURATION,
       @value="PT1H">],
    @comp_name=:VALARM>],
 @comp_name=:VCALENDAR>

Please let me know if this is acceptable.

**Comment by opoudjis** [comment]
And do you want params to be a distinct class instead of a hash?

**Comment by opoudjis** [comment]
Parameters made distinct class
