### ISSUE TITLE
Can't install 0.2.0

### ISSUE THREAD

**Issue by theghall** [riboseinc/ruby-vobject#6]
When I  to bundle install I get:

Could not find ruby-vobject-0.2.0-x86_64-darwin-16 in any of the sources

**Comment by opoudjis** [comment]
Not sure why it would be looking for a binary gem, but I'm seeing that this gem is due for an update anyway. Will try to get to it tonight.

**Comment by opoudjis** [comment]
Released to rubygems as 1.0.0.
