### ISSUE TITLE
Upgrade rsec gem to 1.0 from 0.4

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ruby-vobject#9]

**Comment by opoudjis** [comment]
There's a breakage introduced by rsec 1.0 upgrade, which meant I couldn't get it working, but happy for someone else to work it out.

**Comment by ronaldtse** [comment]
@skalee what's the ETA for this? Thanks.

**Comment by skalee** [comment]
I've just assigned to myself because I am going to solve the other issue. Given the fact there are breaking changes, I suppose it can wait, or not?

**Comment by skalee** [comment]
The breaking change we talk about: https://github.com/luikore/rsec/pull/11. Doesn't look very difficult.

**Comment by ronaldtse** [comment]
@skalee let me know if you can handle it soon. Thanks! 👏

**Comment by ronaldtse** [comment]
@skalee let's keep you busy on the other stuff. :wink:

@alexeymorozov can you help fix this using a PR? Thanks.

**Comment by alexeymorozov** [comment]
Yes, I'm here to help :)

**Comment by alexeymorozov** [comment]
Please look at PR #13

**Comment by ronaldtse** [comment]
Fixed, thanks.
